cloneConcurrency: 8

compressionLevel: 1

enableColors: 1

enableGlobalCache: 1

enableHyperlinks: 1

enableImmutableCache: 0

enableImmutableInstalls: 0

enableInlineBuilds: 1

enableInlineHunks: 1

enableProgressBars: 1

enableStrictSsl: 1

networkConcurrency: 8

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

preferAggregateCacheInfo: 1

preferInteractive: 1

progressBarStyle: patrick
